[project]
name = "water-barons"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pytest>=7.0",
    "hypothesis>=6.0",
    "hyperdiv"
]

[project.scripts]
run = "water_barons.hyperdiv_app:main"
